= Component diagram

[structurizr]
....
workspace {

    model {
        user = person "User" "A user of Expense Tracker."
        softwareSystem = softwareSystem "Expense Tracker" "Allows user to track expenses together with income." {
            backendApp = container "expense-tracker-core" "Handles business logic" "Kotlin and Spring Boot"
            frontendApp = container "expense-tracker-ui" "Handles user interface" "Angular"
            database = container "Postgres Database" "Stores user data" "PostgreSQL" "database"
            keycloak = container "Keycloak IAM" "Handles authentication and authorization" "Keycloak"
        }

        user -> softwareSystem "Uses"

        user -> frontendApp "Uses"
        frontendApp -> backendApp "Sends requests"
        backendApp -> database "Reads from and writes to"
        backendApp -> keycloak "Uses for authentication and authorization"
    }

    views {


        container softwareSystem "ContainerDiagram" {
            include *
            autoLayout
        }

        styles {
            element "Software System" {
                background #1168bd
                color #ffffff
            }
            element "Person" {
                shape person
                background #08427b
                color #ffffff
            }
            element "Container" {
                background #438dd5
                color #ffffff
            }
            element "database" {
                shape Cylinder
            }
        }
    }

}
....
