= ADR 0001: Create single multi-project Gradle build

Date: 2023-07-01

=== Status

Proposed

=== Context

Some important initial decisions must be made on the start of the project which will impact the project probably for all its life-time.
One of the decisions is the general structure of the project and the build tool to use.

Microservice architecture is very popular these days, and it might benefit any project at some point, but it will probably slow down the progress initially. On the other hand, starting with what is called a Modulith would keep things organised and separated until there is actually a need to extract a microservice.

Concerning build tools, Maven is the most popular build tool for Java projects but Gradle has many advantages and is at the moment mature enough to be a valid alternative (in fact most new projects seem to be using Gradle).

=== Decision

We will create a Gradle multi-project build which means that all modules/projects will be part of a parent module/project (and not completely independent as it would be if we used a composite build).

We should consider module separation per bounded context (per DDD, as much as possible).

We will also create one separate module for dependency/version management.

=== Consequences

Using Gradle as build tool has several consequences.
One of them is that the build script is code instead of xml (with all the advantages that this implies).

Using build cache, Gradle daemon and incremental build is (supposed to) increase build time considerably comparing with Maven.

Gradle, mainly because it is code-based, it is very flexible and customizable.
This does not mean that it has a lot of convention-over-configuration options, just that when you need custom flow it is easier to do than in Maven.

One negative consequence of using Gradle is that at the beginning it might take some getting use to, since it is not using the familiar xml syntax.


